import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {PGlite} from '@electric-sql/pglite';
const owner='11111111-1111-4111-8111-111111111111',cashier='22222222-2222-4222-8222-222222222222',analyst='33333333-3333-4333-8333-333333333333',stranger='44444444-4444-4444-8444-444444444444';
let sql=await readFile(new URL('../database/schema.sql',import.meta.url),'utf8');
async function setup(){const db=new PGlite();await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;insert into auth.users values('${owner}'),('${cashier}'),('${analyst}'),('${stranger}');`);await db.exec(sql);await db.exec(`insert into sakhelwe_staff values('${owner}','owner'),('${cashier}','cashier'),('${analyst}','analyst');set role authenticated;set request.jwt.claim.sub='${owner}';`);return db}
const dt=new Date().toISOString().slice(0,10);async function post(db,k,p={},r=crypto.randomUUID()){return(await db.query('select public.sakhelwe_post($1,$2::jsonb,$3::uuid) id',[k,JSON.stringify({date:dt,...p}),r])).rows[0].id}
async function state(db){return(await db.query('select public.sakhelwe_snapshot() s')).rows[0].s}
async function fixtures(db){await post(db,'capital',{amount:'10000'});await post(db,'product',{name:'Chickens',unit:'each',division:'Poultry',threshold:'3'});await post(db,'customer',{name:'Borrower A',phone:''});return state(db)}
const sum=(s,account)=>s.journal.filter(j=>j.account===account).reduce((n,j)=>n+Number(j.debit)-Number(j.credit),0);
test('FIFO sales, credit payments, cash and profit reconcile independently',async()=>{const db=await setup();try{let s=await fixtures(db),p=s.products[0].id,c=s.customers[0].id;await post(db,'receive',{product_id:p,quantity:'10',amount:'500',supplier:'Test'});await post(db,'sale',{product_id:p,quantity:'3',pricing_quantity:'3',price:'80',paid:'100',customer_id:c});s=await state(db);assert.equal(Number(s.batches[0].remaining),7);assert.equal(sum(s,'inventory'),350);assert.equal(sum(s,'cash'),9600);assert.equal(sum(s,'receivables'),140);assert.equal(-sum(s,'revenue')-sum(s,'cost_of_sales'),90);await post(db,'invoice_payment',{invoice_id:s.invoices[0].id,amount:'140'});s=await state(db);assert.equal(sum(s,'receivables'),0);assert.equal(-sum(s,'revenue'),240);assert.equal(sum(s,'cash'),9740);for(const e of s.events)assert.equal(s.journal.filter(j=>j.event_id===e.id).reduce((n,j)=>n+Number(j.debit)-Number(j.credit),0),0)}finally{await db.close()}});
test('insufficient stock and cash roll back all effects',async()=>{const db=await setup();try{let s=await fixtures(db),p=s.products[0].id;await post(db,'receive',{product_id:p,quantity:'1',amount:'50'});let before=await state(db);await assert.rejects(post(db,'sale',{product_id:p,quantity:'2',pricing_quantity:'2',price:'80',paid:'160'}),/not enough stock/);assert.deepEqual(await state(db),before);await assert.rejects(post(db,'expense',{amount:'20000',division:'Poultry',description:'Test expense'}),/not enough operating cash/);assert.deepEqual(await state(db),before);await assert.rejects(post(db,'receive',{product_id:p,quantity:'1.5',amount:'20'}),/valid quantity/)}finally{await db.close()}});
test('idempotent retries and payload mismatch protection',async()=>{const db=await setup();try{await fixtures(db);const key=crypto.randomUUID(),id=await post(db,'expense',{amount:'10',division:'Business',description:'Transport'},key);const before=await state(db);assert.equal(await post(db,'expense',{amount:'10',division:'Business',description:'Transport'},key),id);assert.deepEqual(await state(db),before);await assert.rejects(post(db,'expense',{amount:'20',division:'Business',description:'Transport'},key),/another entry/)}finally{await db.close()}});
test('loan eligibility, repayment allocation, settlement and overpayment rejection',async()=>{const db=await setup();try{let s=await fixtures(db),c=s.customers[0].id;await post(db,'policy',{name:'Zero annual test',annual_rate:'0',approved:'yes'});s=await state(db);const payload={customer_id:c,policy_id:s.policies[0].id,amount:'100',due_on:dt};let id=await post(db,'loan',payload);await assert.rejects(post(db,'loan',payload),/clear existing debt/);let before=await state(db);await assert.rejects(post(db,'repay',{loan_id:id,amount:'101'}),/exceeds/);assert.deepEqual(await state(db),before);await post(db,'repay',{loan_id:id,amount:'100'});s=await state(db);assert.equal(s.loans[0].status,'settled');assert.equal(sum(s,'principal'),0);assert.equal(sum(s,'interest_income'),0);assert.equal(sum(s,'cash'),10000);await post(db,'loan',payload)}finally{await db.close()}});
test('access rules block unapproved staff, analyst writes and direct table changes',async()=>{const db=await setup();try{await fixtures(db);await db.exec(`set request.jwt.claim.sub='${stranger}'`);await assert.rejects(state(db),/not been granted/);assert.equal((await db.query('select * from sakhelwe_customers')).rows.length,0);await assert.rejects(post(db,'capital',{amount:'20'}),/cannot record/);await db.exec(`set request.jwt.claim.sub='${analyst}'`);await state(db);await assert.rejects(post(db,'expense',{amount:'10'}),/cannot record/);await assert.rejects(db.exec('delete from sakhelwe_events'),/permission denied/);await db.exec(`set request.jwt.claim.sub='${cashier}'`);await assert.rejects(post(db,'capital',{amount:'20'}),/Only the owner/)}finally{await db.close()}});
test('exact interest accrual and repayment use dated principal',async()=>{const db=await setup();try{await db.exec('reset role');await db.exec(`insert into sakhelwe_products(name,unit,division) values('Test','each','Poultry')`);await db.exec('set role authenticated');const past=new Date(Date.now()-10*86400000).toISOString().slice(0,10);await post(db,'capital',{date:past,amount:'10000'});await post(db,'customer',{date:past,name:'Interest borrower'});await post(db,'policy',{date:past,name:'Interest test',annual_rate:'36.5',approved:'yes'});let s=await state(db);const id=await post(db,'loan',{date:past,amount:'1000',customer_id:s.customers[0].id,policy_id:s.policies[0].id,due_on:dt});await post(db,'repay',{loan_id:id,amount:'110'});s=await state(db);assert.equal(Number(s.loans[0].principal),900);assert.equal(Number(s.loans[0].interest),0);assert.equal(-sum(s,'interest_income'),10);assert.equal(sum(s,'cash'),9110);await post(db,'accrue',{loan_id:id});s=await state(db);assert.equal(-sum(s,'interest_income'),10);await assert.rejects(post(db,'repay',{date:past,loan_id:id,amount:'10'}),/date is earlier/)}finally{await db.close()}});
