import {test} from 'node:test';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';import {readFile,readdir} from 'node:fs/promises';import {JSDOM} from 'jsdom';
const assets=await readdir(new URL('../dist/assets',import.meta.url)),bundle=await readFile(new URL('../dist/assets/'+assets.find(f=>f.endsWith('.js')),import.meta.url),'utf8');
const tick=()=>new Promise(resolve=>setTimeout(resolve,60));
test('built interface opens sample workspace, navigates all pages and records a delivery',async()=>{
 const dom=new JSDOM('<!doctype html><div id="root"></div>',{url:'https://sakhelwe.example',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window,doc=w.document,errors=[];w.addEventListener('error',e=>errors.push(e.error?.message||e.message));
 w.structuredClone=structuredClone;try{w.eval(bundle);await tick();assert.match(doc.body.textContent,/Welcome back/);assert.match(doc.body.textContent,/Sign in to your business workspace/);
 const button=text=>[...doc.querySelectorAll('button')].find(x=>x.textContent.trim()===text);
 button('Open sample workspace').click();await tick();assert.match(doc.body.textContent,/Business overview/);assert.match(doc.body.textContent,/E 7,510.00/);assert.match(doc.body.textContent,/E 1,230.00/);
 for(const name of ['Chickens','Pigs','Sales','Customers','Loans','Expenses','Reports','Settings','Overview']){[...doc.querySelectorAll('nav button')].find(b=>b.textContent.startsWith(name)).click();await tick();assert.equal(doc.querySelector('.page-heading h1').textContent,name==='Overview'?'Business overview':name);}
 button('Receive a deliveryAdd stock and purchase cost').click();await tick();const form=doc.querySelector('.modal form');assert.ok(form);
 const select=form.querySelector('[name=product_id]');select.value='chicken';select.dispatchEvent(new w.Event('change',{bubbles:true}));await tick();
 const input=form.querySelector('[name=quantity]');Object.getOwnPropertyDescriptor(w.HTMLInputElement.prototype,'value').set.call(input,'5');input.dispatchEvent(new w.Event('input',{bubbles:true}));await tick();
 form.querySelector('[name=supplier]').value='UI test supplier';form.querySelector('[name=amount]').value='300';form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await tick();assert.match(doc.body.textContent,/Demo entry saved/);assert.equal(doc.querySelector('[aria-labelledby=form-title]'),null);assert.match(doc.body.textContent,/E 7,210.00/);assert.deepEqual(errors,[]);
 }finally{w.close()}
});test('owner setup pre-fills approved email and rejects mismatched passwords',async()=>{const dom=new JSDOM('<div id="root"></div>',{url:'https://sakhelwe.example',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window,doc=w.document;w.structuredClone=structuredClone;try{w.eval(bundle);await tick();[...doc.querySelectorAll('button')].find(b=>b.textContent==='First time? Create owner account').click();await tick();assert.equal(doc.querySelector('[name=email]').value,'sakhelweinvestment@gmail.com');assert.equal(doc.querySelector('[name=email]').readOnly,true);doc.querySelector('[name=password]').value='test-password-123';doc.querySelector('[name=confirm_password]').value='different-password';doc.querySelector('form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await tick();assert.match(doc.body.textContent,/passwords do not match/);}finally{w.close()}});
test('signed-in interface queues offline entry then confirms it on reconnect',async()=>{const user='11111111-1111-4111-8111-111111111111';const dom=new JSDOM('<div id="root"></div>',{url:'https://sakhelwe.example',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window,doc=w.document;const {indexedDB}=await import('fake-indexeddb');w.indexedDB=indexedDB;w.structuredClone=structuredClone;let online=true,state={role:'owner',products:[],customers:[],events:[],batches:[],invoices:[],loans:[],journal:[]},posts=0;Object.defineProperty(w.navigator,'onLine',{get:()=>online});w.fetch=async(url,options)=>{if(!online)throw Error('Offline');if(String(url).includes('sakhelwe_sync_post')){posts++;const p=JSON.parse(options.body);assert.equal(p.expected_user_id,user);state.events.push({id:p.request_key,request_key:p.request_key,kind:p.kind,business_date:p.payload.date,division:'Business',amount:100,payload:p.payload});state.journal.push({event_id:p.request_key,account:'cash',debit:100,credit:0});return new Response(JSON.stringify(p.request_key),{headers:{'content-type':'application/json'}})}return new Response(JSON.stringify(state),{headers:{'content-type':'application/json'}})};w.localStorage.setItem('sb-hkwmhajogglgqvmxxrxs-auth-token',JSON.stringify({access_token:'test-token',refresh_token:'test-refresh',token_type:'bearer',expires_at:Math.floor(Date.now()/1000)+3600,expires_in:3600,user:{id:user,email:'sakhelweinvestment@gmail.com'}}));try{w.eval(bundle);await tick();await tick();await tick();assert.match(doc.body.textContent,/Cloud records up to date/);online=false;w.dispatchEvent(new w.Event('offline'));[...doc.querySelectorAll('nav button')].find(b=>b.textContent==='Settings').click();await tick();[...doc.querySelectorAll('button')].find(b=>b.textContent==='Record capital').click();await tick();doc.querySelector('.modal [name=amount]').value='100';doc.querySelector('.modal form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await tick();await tick();assert.match(doc.body.textContent,/1 pending entry/);assert.equal(posts,0);online=true;w.dispatchEvent(new w.Event('online'));await tick();await tick();await tick();assert.equal(posts,1);assert.match(doc.body.textContent,/Cloud records up to date/);}finally{w.close()}});
